# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# Look for ROS bb and bbappends in the layer, please add your DISTRO here if you need ROS support
BBFILES +="${@base_contains('DISTRO', 'robot-som-ros'," ${LAYERDIR}/recipes/ros/recipes*/*/*.bb ${LAYERDIR}/recipes/ros/recipes*/*/*.bbappend ${LAYERDIR}/recipes/recipes-common/*/*.bb ${LAYERDIR}/recipes/recipes-common/*/*.bbappend ${LAYERDIR}/recipes-products/images/ros/*.bbappend ", '', d)}"
#BBFILES +="${@base_contains('DISTRO', 'robot'," ${LAYERDIR}/recipes/ros/recipes*/*/*.bb ${LAYERDIR}/recipes/ros/recipes*/*/*.bbappend ${LAYERDIR}/recipes/recipes-common/*/*.bb ${LAYERDIR}/recipes/recipes-common/*/*.bbappend ${LAYERDIR}/recipes-products/images/ros/*.bbappend ", '', d)}"

# Look for ROS2 bb and bbappends in the layer, please add your DISTRO here if you need ROS2 support
BBFILES +="${@base_contains('DISTRO', 'robot'," ${LAYERDIR}/recipes/ros2/recipes*/*/*.bb ${LAYERDIR}/recipes/ros2/recipes*/*/*.bbappend ${LAYERDIR}/recipes/recipes-common/*/*.bb ${LAYERDIR}/recipes/recipes-common/*/*.bbappend ${LAYERDIR}/recipes-products/images/ros2/*.bbappend ", '', d)}"

BBFILE_COLLECTIONS += "ros-layer"
BBFILE_PATTERN_ros-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_ros-layer = "7"

LICENSE_PATH += "${LAYERDIR}/recipes/ros/licenses"

ROSDISTRO := "indigo"
